spring.application.name=ms-products
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB}

# Logging (reduce overhead)
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.com.mongodb=INFO
logging.level.com.maovares=INFO

# Client certificate thumbprint for validation (i.e. E2:92:70:E9:47:8D:A9:EA:1B:6F:75:04:ED:XX:XX:XX:XX:XX:XX:XX)
client.cert.thumbprint=${CLIENT_CERT_THUMBPRINT}
